-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema csgoanalysis_appdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema csgoanalysis_appdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `csgoanalysis_appdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `csgoanalysis_appdb` ;

-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`game` (
  `ID` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `demoName` TEXT NULL DEFAULT NULL,
  `matchName` TEXT NULL DEFAULT NULL,
  `clientName` TEXT NULL DEFAULT NULL,
  `mapName` TEXT NULL DEFAULT NULL,
  `tickRate` TINYINT UNSIGNED NULL DEFAULT NULL,
  `playbackTicks` INT UNSIGNED NULL DEFAULT NULL,
  `parseRate` TINYINT UNSIGNED NULL DEFAULT NULL,
  `valid` BIT(1) NULL DEFAULT b'1',
  `createdTimestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`player`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`player` (
  `ID` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `steamID` CHAR(17) NULL DEFAULT NULL,
  `name` TEXT NULL DEFAULT NULL,
  `teamName` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`round`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`round` (
  `roundNum` SMALLINT UNSIGNED NOT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `startTick` INT UNSIGNED NULL DEFAULT NULL,
  `freezeTimeEndTick` INT UNSIGNED NULL DEFAULT NULL,
  `endTick` INT UNSIGNED NULL DEFAULT NULL,
  `endOfficialTick` INT UNSIGNED NULL DEFAULT NULL,
  `tScore` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctScore` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `endTScore` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `endCTScore` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tTeam` TEXT NULL DEFAULT NULL,
  `ctTeam` TEXT NULL DEFAULT NULL,
  `winningSide` VARCHAR(2) NULL DEFAULT NULL,
  `winningTeam` TEXT NULL DEFAULT NULL,
  `losingTeam` TEXT NULL DEFAULT NULL,
  `roundEndReason` TEXT NULL DEFAULT NULL,
  `ctFreezeTimeEndEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctRoundStartEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctRoundSpendMoney` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctBuyType` TEXT NULL DEFAULT NULL,
  `tFreezeTimeEndEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tRoundStartEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tRoundSpendMoney` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tBuyType` TEXT NULL DEFAULT NULL,
  `endTickCorrect` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`matchID`, `roundNum`),
  CONSTRAINT `FK_round_game`
    FOREIGN KEY (`matchID`)
    REFERENCES `csgoanalysis_appdb`.`game` (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`frame`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`frame` (
  `bombPlanted` BIT(1) NULL DEFAULT NULL,
  `bomb_x` DOUBLE NULL DEFAULT NULL,
  `bomb_y` DOUBLE NULL DEFAULT NULL,
  `bomb_z` DOUBLE NULL DEFAULT NULL,
  `bombsite` CHAR(1) NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `ctAlivePlayers` TINYINT NULL DEFAULT NULL,
  `ctEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctName` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_1_Flashbang` TINYINT NULL DEFAULT NULL,
  `ctPlayer_1_HEGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_1_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_1_activeWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_eyeX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_eyeY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_eyeZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_fireGrenades` TINYINT NULL DEFAULT NULL,
  `ctPlayer_1_hasBomb` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_1_isAirborne` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isAlive` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isBlinded` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isBot` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isDefusing` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isDucking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isPlanting` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isReloading` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isScoped` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isStanding` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isUnknown` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_isWalking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_1_lastPlaceName` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_mainWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_ping` SMALLINT NULL DEFAULT NULL,
  `ctPlayer_1_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_spotters` TEXT NULL DEFAULT NULL,
  `ctPlayer_1_velocityX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_velocityY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_velocityZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_viewX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_viewY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_x` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_y` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_z` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_1_zoomLevel` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_Flashbang` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_HEGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_activeWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_2_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_eyeX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_eyeY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_eyeZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_fireGrenades` TINYINT NULL DEFAULT NULL,
  `ctPlayer_2_hasBomb` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_2_isAirborne` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isAlive` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isBlinded` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isBot` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isDefusing` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isDucking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isPlanting` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isReloading` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isScoped` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isStanding` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isUnknown` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_isWalking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_2_lastPlaceName` TEXT NULL DEFAULT NULL,
  `ctPlayer_2_mainWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_2_ping` SMALLINT NULL DEFAULT NULL,
  `ctPlayer_2_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_2_spotters` TEXT NULL DEFAULT NULL,
  `ctPlayer_2_velocityX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_velocityY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_velocityZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_viewX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_viewY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_x` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_y` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_z` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_2_zoomLevel` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_Flashbang` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_HEGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_activeWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_3_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_eyeX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_eyeY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_eyeZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_fireGrenades` TINYINT NULL DEFAULT NULL,
  `ctPlayer_3_hasBomb` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_3_isAirborne` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isAlive` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isBlinded` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isBot` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isDefusing` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isDucking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isPlanting` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isReloading` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isScoped` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isStanding` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isUnknown` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_isWalking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_3_lastPlaceName` TEXT NULL DEFAULT NULL,
  `ctPlayer_3_mainWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_3_ping` SMALLINT NULL DEFAULT NULL,
  `ctPlayer_3_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_3_spotters` TEXT NULL DEFAULT NULL,
  `ctPlayer_3_velocityX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_velocityY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_velocityZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_viewX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_viewY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_x` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_y` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_z` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_3_zoomLevel` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_Flashbang` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_HEGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_activeWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_4_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_eyeX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_eyeY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_eyeZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_fireGrenades` TINYINT NULL DEFAULT NULL,
  `ctPlayer_4_hasBomb` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_4_isAirborne` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isAlive` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isBlinded` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isBot` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isDefusing` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isDucking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isPlanting` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isReloading` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isScoped` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isStanding` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isUnknown` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_isWalking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_4_lastPlaceName` TEXT NULL DEFAULT NULL,
  `ctPlayer_4_mainWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_4_ping` SMALLINT NULL DEFAULT NULL,
  `ctPlayer_4_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_4_spotters` TEXT NULL DEFAULT NULL,
  `ctPlayer_4_velocityX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_velocityY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_velocityZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_viewX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_viewY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_x` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_y` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_z` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_4_zoomLevel` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_Flashbang` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_HEGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_activeWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_5_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_eyeX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_eyeY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_eyeZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_fireGrenades` TINYINT NULL DEFAULT NULL,
  `ctPlayer_5_hasBomb` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `ctPlayer_5_isAirborne` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isAlive` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isBlinded` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isBot` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isDefusing` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isDucking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isPlanting` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isReloading` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isScoped` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isStanding` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isUnknown` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_isWalking` BIT(1) NULL DEFAULT NULL,
  `ctPlayer_5_lastPlaceName` TEXT NULL DEFAULT NULL,
  `ctPlayer_5_mainWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_5_ping` SMALLINT NULL DEFAULT NULL,
  `ctPlayer_5_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `ctPlayer_5_spotters` TEXT NULL DEFAULT NULL,
  `ctPlayer_5_velocityX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_velocityY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_velocityZ` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_viewX` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_viewY` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_x` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_y` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_z` DOUBLE NULL DEFAULT NULL,
  `ctPlayer_5_zoomLevel` TINYINT NULL DEFAULT NULL,
  `ctTotalUtility` TINYINT NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `tAlivePlayers` TINYINT NULL DEFAULT NULL,
  `tEqVal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tName` TEXT NULL DEFAULT NULL,
  `tPlayer_1_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_1_Flashbang` TINYINT NULL DEFAULT NULL,
  `tPlayer_1_HEGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_1_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_1_activeWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_1_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_eyeX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_eyeY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_eyeZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_fireGrenades` TINYINT NULL DEFAULT NULL,
  `tPlayer_1_hasBomb` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_1_isAirborne` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isAlive` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isBlinded` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isBot` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isDefusing` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isDucking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isPlanting` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isReloading` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isScoped` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isStanding` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isUnknown` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_isWalking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_1_lastPlaceName` TEXT NULL DEFAULT NULL,
  `tPlayer_1_mainWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_1_ping` SMALLINT NULL DEFAULT NULL,
  `tPlayer_1_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_1_spotters` TEXT NULL DEFAULT NULL,
  `tPlayer_1_velocityX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_velocityY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_velocityZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_viewX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_viewY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_x` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_y` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_z` DOUBLE NULL DEFAULT NULL,
  `tPlayer_1_zoomLevel` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_Flashbang` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_HEGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_activeWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_2_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_eyeX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_eyeY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_eyeZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_fireGrenades` TINYINT NULL DEFAULT NULL,
  `tPlayer_2_hasBomb` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_2_isAirborne` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isAlive` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isBlinded` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isBot` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isDefusing` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isDucking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isPlanting` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isReloading` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isScoped` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isStanding` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isUnknown` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_isWalking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_2_lastPlaceName` TEXT NULL DEFAULT NULL,
  `tPlayer_2_mainWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_2_ping` SMALLINT NULL DEFAULT NULL,
  `tPlayer_2_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_2_spotters` TEXT NULL DEFAULT NULL,
  `tPlayer_2_velocityX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_velocityY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_velocityZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_viewX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_viewY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_x` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_y` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_z` DOUBLE NULL DEFAULT NULL,
  `tPlayer_2_zoomLevel` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_Flashbang` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_HEGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_activeWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_3_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_eyeX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_eyeY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_eyeZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_fireGrenades` TINYINT NULL DEFAULT NULL,
  `tPlayer_3_hasBomb` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_3_isAirborne` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isAlive` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isBlinded` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isBot` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isDefusing` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isDucking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isPlanting` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isReloading` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isScoped` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isStanding` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isUnknown` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_isWalking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_3_lastPlaceName` TEXT NULL DEFAULT NULL,
  `tPlayer_3_mainWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_3_ping` SMALLINT NULL DEFAULT NULL,
  `tPlayer_3_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_3_spotters` TEXT NULL DEFAULT NULL,
  `tPlayer_3_velocityX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_velocityY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_velocityZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_viewX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_viewY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_x` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_y` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_z` DOUBLE NULL DEFAULT NULL,
  `tPlayer_3_zoomLevel` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_Flashbang` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_HEGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_activeWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_4_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_eyeX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_eyeY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_eyeZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_fireGrenades` TINYINT NULL DEFAULT NULL,
  `tPlayer_4_hasBomb` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_4_isAirborne` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isAlive` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isBlinded` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isBot` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isDefusing` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isDucking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isPlanting` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isReloading` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isScoped` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isStanding` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isUnknown` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_isWalking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_4_lastPlaceName` TEXT NULL DEFAULT NULL,
  `tPlayer_4_mainWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_4_ping` SMALLINT NULL DEFAULT NULL,
  `tPlayer_4_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_4_spotters` TEXT NULL DEFAULT NULL,
  `tPlayer_4_velocityX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_velocityY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_velocityZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_viewX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_viewY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_x` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_y` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_z` DOUBLE NULL DEFAULT NULL,
  `tPlayer_4_zoomLevel` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_DecoyGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_Flashbang` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_HEGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_ID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_SmokeGrenade` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_activeWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_5_armor` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_cash` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_cashSpendThisRound` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_cashSpendTotal` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_equipmentValue` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_equipmentValueFreezetimeEnd` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_equipmentValueRoundStart` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_eyeX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_eyeY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_eyeZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_fireGrenades` TINYINT NULL DEFAULT NULL,
  `tPlayer_5_hasBomb` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_hasDefuse` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_hasHelmet` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_hp` TINYINT UNSIGNED NULL DEFAULT NULL,
  `tPlayer_5_isAirborne` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isAlive` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isBlinded` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isBot` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isDefusing` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isDucking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isInBombZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isInBuyZone` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isPlanting` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isReloading` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isScoped` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isStanding` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isUnDuckingInProgress` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isUnknown` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_isWalking` BIT(1) NULL DEFAULT NULL,
  `tPlayer_5_lastPlaceName` TEXT NULL DEFAULT NULL,
  `tPlayer_5_mainWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_5_ping` SMALLINT NULL DEFAULT NULL,
  `tPlayer_5_secondaryWeapon` TEXT NULL DEFAULT NULL,
  `tPlayer_5_spotters` TEXT NULL DEFAULT NULL,
  `tPlayer_5_velocityX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_velocityY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_velocityZ` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_viewX` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_viewY` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_x` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_y` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_z` DOUBLE NULL DEFAULT NULL,
  `tPlayer_5_zoomLevel` TINYINT NULL DEFAULT NULL,
  `tTotalUtility` TINYINT NULL DEFAULT NULL,
  `tick` INT UNSIGNED NOT NULL,
  `importantMoment` BIT(1) NULL DEFAULT NULL,
  `ctPrediction` DOUBLE NULL DEFAULT NULL,
  PRIMARY KEY (`matchID`, `tick`),
  INDEX `FK_frame_player_ct1_idx` (`ctPlayer_1_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_ct2_idx` (`ctPlayer_2_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_ct3_idx` (`ctPlayer_3_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_ct4_idx` (`ctPlayer_4_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_ct5_idx` (`ctPlayer_5_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_t1_idx` (`tPlayer_1_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_t2_idx` (`tPlayer_2_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_t3_idx` (`tPlayer_3_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_t4_idx` (`tPlayer_4_ID` ASC) VISIBLE,
  INDEX `FK_frame_player_t5_idx` (`tPlayer_5_ID` ASC) VISIBLE,
  INDEX `FK_frame_round_idx` (`matchID` ASC, `roundNum` ASC) VISIBLE,
  CONSTRAINT `FK_frame_game`
    FOREIGN KEY (`matchID`)
    REFERENCES `csgoanalysis_appdb`.`game` (`ID`),
  CONSTRAINT `FK_frame_player_ct1`
    FOREIGN KEY (`ctPlayer_1_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_ct2`
    FOREIGN KEY (`ctPlayer_2_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_ct3`
    FOREIGN KEY (`ctPlayer_3_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_ct4`
    FOREIGN KEY (`ctPlayer_4_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_ct5`
    FOREIGN KEY (`ctPlayer_5_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_t1`
    FOREIGN KEY (`tPlayer_1_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_t2`
    FOREIGN KEY (`tPlayer_2_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_t3`
    FOREIGN KEY (`tPlayer_3_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_t4`
    FOREIGN KEY (`tPlayer_4_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_player_t5`
    FOREIGN KEY (`tPlayer_5_ID`)
    REFERENCES `csgoanalysis_appdb`.`player` (`ID`),
  CONSTRAINT `FK_frame_round`
    FOREIGN KEY (`matchID` , `roundNum`)
    REFERENCES `csgoanalysis_appdb`.`round` (`matchID` , `roundNum`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`bombevent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`bombevent` (
  `tick` INT UNSIGNED NOT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `playerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `playerX` DOUBLE NULL DEFAULT NULL,
  `playerY` DOUBLE NULL DEFAULT NULL,
  `playerZ` DOUBLE NULL DEFAULT NULL,
  `bombAction` TEXT NULL DEFAULT NULL,
  `bombSite` CHAR(1) NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `tick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`matchID`, `tick`),
  INDEX `FK_bombevent_frame_idx` (`matchID` ASC, `tick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_bombevent_frame`
    FOREIGN KEY (`matchID` , `tick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`damage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`damage` (
  `tick` INT UNSIGNED NULL DEFAULT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `attackerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `attackerSide` VARCHAR(2) NULL DEFAULT NULL,
  `attackerX` DOUBLE NULL DEFAULT NULL,
  `attackerY` DOUBLE NULL DEFAULT NULL,
  `attackerZ` DOUBLE NULL DEFAULT NULL,
  `attackerViewX` DOUBLE NULL DEFAULT NULL,
  `attackerViewY` DOUBLE NULL DEFAULT NULL,
  `attackerStrafe` BIT(1) NULL DEFAULT NULL,
  `victimID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `victimSide` VARCHAR(2) NULL DEFAULT NULL,
  `victimX` DOUBLE NULL DEFAULT NULL,
  `victimY` DOUBLE NULL DEFAULT NULL,
  `victimZ` DOUBLE NULL DEFAULT NULL,
  `victimViewX` DOUBLE NULL DEFAULT NULL,
  `victimViewY` DOUBLE NULL DEFAULT NULL,
  `weapon` TEXT NULL DEFAULT NULL,
  `weaponClass` TEXT NULL DEFAULT NULL,
  `hpDamage` SMALLINT NULL DEFAULT NULL,
  `hpDamageTaken` TINYINT NULL DEFAULT NULL,
  `armorDamage` SMALLINT NULL DEFAULT NULL,
  `armorDamageTaken` TINYINT NULL DEFAULT NULL,
  `hitGroup` TEXT NULL DEFAULT NULL,
  `isFriendlyFire` BIT(1) NULL DEFAULT NULL,
  `distance` DOUBLE NULL DEFAULT NULL,
  `zoomLevel` TINYINT NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `tick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `ID` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`matchID`, `ID`),
  INDEX `FK_damage_frame_idx` (`matchID` ASC, `tick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_damage_frame`
    FOREIGN KEY (`matchID` , `tick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`elimination`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`elimination` (
  `tick` INT UNSIGNED NULL DEFAULT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `attackerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `attackerSide` VARCHAR(2) NULL DEFAULT NULL,
  `attackerX` DOUBLE NULL DEFAULT NULL,
  `attackerY` DOUBLE NULL DEFAULT NULL,
  `attackerZ` DOUBLE NULL DEFAULT NULL,
  `attackerViewX` DOUBLE NULL DEFAULT NULL,
  `attackerViewY` DOUBLE NULL DEFAULT NULL,
  `victimID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `victimSide` VARCHAR(2) NULL DEFAULT NULL,
  `victimX` DOUBLE NULL DEFAULT NULL,
  `victimY` DOUBLE NULL DEFAULT NULL,
  `victimZ` DOUBLE NULL DEFAULT NULL,
  `victimViewX` DOUBLE NULL DEFAULT NULL,
  `victimViewY` DOUBLE NULL DEFAULT NULL,
  `assisterID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `assisterSide` VARCHAR(2) NULL DEFAULT NULL,
  `isSuicide` BIT(1) NULL DEFAULT NULL,
  `isTeamkill` BIT(1) NULL DEFAULT NULL,
  `isWallbang` BIT(1) NULL DEFAULT NULL,
  `penetratedObjects` TINYINT NULL DEFAULT NULL,
  `isFirstKill` BIT(1) NULL DEFAULT NULL,
  `isHeadshot` BIT(1) NULL DEFAULT NULL,
  `victimBlinded` BIT(1) NULL DEFAULT NULL,
  `attackerBlinded` BIT(1) NULL DEFAULT NULL,
  `flashThrowerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `flashThrowerSide` VARCHAR(2) NULL DEFAULT NULL,
  `noScope` BIT(1) NULL DEFAULT NULL,
  `thruSmoke` BIT(1) NULL DEFAULT NULL,
  `distance` DOUBLE NULL DEFAULT NULL,
  `isTrade` BIT(1) NULL DEFAULT NULL,
  `playerTradedID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `weapon` TEXT NULL DEFAULT NULL,
  `weaponClass` TEXT NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `tick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `ID` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`matchID`, `ID`),
  INDEX `FK_elimination_frame_idx` (`matchID` ASC, `tick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_elimination_frame`
    FOREIGN KEY (`matchID` , `tick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`flash`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`flash` (
  `tick` INT UNSIGNED NULL DEFAULT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `attackerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `attackerSide` VARCHAR(2) NULL DEFAULT NULL,
  `attackerX` DOUBLE NULL DEFAULT NULL,
  `attackerY` DOUBLE NULL DEFAULT NULL,
  `attackerZ` DOUBLE NULL DEFAULT NULL,
  `attackerViewX` DOUBLE NULL DEFAULT NULL,
  `attackerViewY` DOUBLE NULL DEFAULT NULL,
  `playerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `playerSide` VARCHAR(2) NULL DEFAULT NULL,
  `playerX` DOUBLE NULL DEFAULT NULL,
  `playerY` DOUBLE NULL DEFAULT NULL,
  `playerZ` DOUBLE NULL DEFAULT NULL,
  `playerViewX` DOUBLE NULL DEFAULT NULL,
  `playerViewY` DOUBLE NULL DEFAULT NULL,
  `flashDuration` DOUBLE NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `ID` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`matchID`, `ID`),
  INDEX `FK_flash_frame_idx` (`matchID` ASC, `tick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_flash_frame`
    FOREIGN KEY (`matchID` , `tick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`grenade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`grenade` (
  `throwTick` INT UNSIGNED NULL DEFAULT NULL,
  `destroyTick` INT UNSIGNED NULL DEFAULT NULL,
  `throwSeconds` DOUBLE NULL DEFAULT NULL,
  `throwClockTime` CHAR(5) NULL DEFAULT NULL,
  `destroySeconds` DOUBLE NULL DEFAULT NULL,
  `destroyClockTime` CHAR(5) NULL DEFAULT NULL,
  `throwerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `throwerSide` VARCHAR(2) NULL DEFAULT NULL,
  `throwerX` DOUBLE NULL DEFAULT NULL,
  `throwerY` DOUBLE NULL DEFAULT NULL,
  `throwerZ` DOUBLE NULL DEFAULT NULL,
  `grenadeType` TEXT NULL DEFAULT NULL,
  `grenadeX` DOUBLE NULL DEFAULT NULL,
  `grenadeY` DOUBLE NULL DEFAULT NULL,
  `grenadeZ` DOUBLE NULL DEFAULT NULL,
  `entityId` CHAR(19) NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `throwTick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `destroyTick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `ID` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`matchID`, `ID`),
  INDEX `FK_grenade_frame_idx` (`matchID` ASC, `throwTick_parsed` ASC) VISIBLE,
  INDEX `FK_grenade_frame2_idx` (`matchID` ASC, `destroyTick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_grenade_frame`
    FOREIGN KEY (`matchID` , `throwTick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`),
  CONSTRAINT `FK_grenade_frame2`
    FOREIGN KEY (`matchID` , `destroyTick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`rating` (
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `tick` INT UNSIGNED NULL DEFAULT NULL,
  `playerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `gainValue` DOUBLE NULL DEFAULT NULL,
  `type` TEXT NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `ID` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`ID`, `matchID`),
  INDEX `FK_rating_frame_idx` (`matchID` ASC, `tick` ASC) VISIBLE,
  CONSTRAINT `FK_rating_frame`
    FOREIGN KEY (`matchID` , `tick`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `csgoanalysis_appdb`.`weaponfire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `csgoanalysis_appdb`.`weaponfire` (
  `tick` INT UNSIGNED NULL DEFAULT NULL,
  `seconds` DOUBLE NULL DEFAULT NULL,
  `clockTime` CHAR(5) NULL DEFAULT NULL,
  `playerID` MEDIUMINT UNSIGNED NULL DEFAULT NULL,
  `playerSide` VARCHAR(2) NULL DEFAULT NULL,
  `playerX` DOUBLE NULL DEFAULT NULL,
  `playerY` DOUBLE NULL DEFAULT NULL,
  `playerZ` DOUBLE NULL DEFAULT NULL,
  `playerViewX` DOUBLE NULL DEFAULT NULL,
  `playerViewY` DOUBLE NULL DEFAULT NULL,
  `playerStrafe` BIT(1) NULL DEFAULT NULL,
  `weapon` TEXT NULL DEFAULT NULL,
  `weaponClass` TEXT NULL DEFAULT NULL,
  `ammoInMagazine` SMALLINT NULL DEFAULT NULL,
  `ammoInReserve` SMALLINT NULL DEFAULT NULL,
  `zoomLevel` TINYINT NULL DEFAULT NULL,
  `roundNum` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `matchID` SMALLINT UNSIGNED NOT NULL,
  `tick_parsed` INT UNSIGNED NULL DEFAULT NULL,
  `ID` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`matchID`, `ID`),
  INDEX `FK_weaponfire_frame_idx` (`matchID` ASC, `tick_parsed` ASC) VISIBLE,
  CONSTRAINT `FK_weaponfire_frame`
    FOREIGN KEY (`matchID` , `tick_parsed`)
    REFERENCES `csgoanalysis_appdb`.`frame` (`matchID` , `tick`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
